In [1]:
import numpy as np 
# generate a random matrix of order 4X3 
m = np.random.rand(4,3) 
m

array([[0.33769592, 0.65156364, 0.08633031],
       [0.35416524, 0.0565022 , 0.1239478 ],
       [0.18984336, 0.77908977, 0.4239706 ],
       [0.85979632, 0.94029535, 0.22066617]])

In [2]:
# Singular Value Decomposition (SVD) 
U,S,VT = np.linalg.svd(m) 

In [3]:
U

array([[-0.42514575,  0.09603637,  0.56178312, -0.70315562],
       [-0.15764175, -0.47486292, -0.69104177, -0.52164696],
       [-0.4869214 ,  0.75288058, -0.44048303,  0.04531081],
       [-0.74653045, -0.44548069,  0.1132947 ,  0.48104422]])

In [ ]:
S

array([1.7099151 , 0.46005386, 0.22232197])

In [5]:
VT

array([[-0.54605293, -0.79959012, -0.24996369],
       [-0.81695244,  0.44216812,  0.37023785],
       [-0.18551255,  0.40637791, -0.89467429]])